openapi: "3.0.0"
info:
  version: 1.0.0
  title: University Domains and Names Data List & API
  license:
    name: MIT
servers:
  - url: http://universities.hipolabs.com/
paths:
  /search:
    get:
      summary: Search universities
      operationId: searchUniversities
      tags:
        - universities
      parameters:
        - name: country
          in: query
          description: Country
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: How many items to return at one time
          required: false
          schema:
            type: integer
            maximum: 20
            format: int32
      responses:
        '200':
          description: An array of universities
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Universities"
components:
  schemas:
    University:
      type: object
      properties:
        alpha_two_code:
          type: string
        web_pages:
          type: array
          items:
            type: string
        name:
          type: string
        country:
          type: string
        state-province:
          type: string
        domains:
          type: array
          items:
            type: string
    Universities:
      type: array
      items:
        $ref: "#/components/schemas/University"